#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080
sed -i "s/#user www-data/user www-data/" /etc/nginx/nginx.conf
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill apache2
service nginx start