#!/usr/bin/env bash
# Fix Nginx to listen on port 80
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080/listen [::]:80/g' /etc/nginx/sites-enabled/default
service nginx restart
