#!/usr/bin/env bash
# Installs and configures nginx to serve a page containing Holberton School

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

service nginx start
service nginx restart
