#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page
# The redirection is a "301 Moved Permanently"

sudo apt-get update
sudo apt-get -y install nginx ufw
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Add redirect rule for /redirect_me using a rewrite rule
sudo sed -i 's|server_name _;|server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/ permanent;|' /etc/nginx/sites-available/default

sudo service nginx restart